#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# keys.cmake
#
# Converts PEM public-key files and binary verification-message files from the
# keys/ directory into C byte-array headers that are compiled into the application.
#
# Outputs (placed in ${CMAKE_BINARY_DIR}/generated/):
#   provisioned_keys.h   - public-key byte arrays + metadata
#   image_digests.h      - expected SHA-256 digests for BL1 / BL2 / app candidate
#

set(MFG_KEYS_DIR   ${CMAKE_CURRENT_SOURCE_DIR}/keys)
set(MFG_GEN_DIR    ${CMAKE_BINARY_DIR}/generated)

file(MAKE_DIRECTORY ${MFG_GEN_DIR})

# ---------------------------------------------------------------------------
# Collect every .pem file found directly inside keys/
# ---------------------------------------------------------------------------
file(GLOB MFG_PEM_FILES "${MFG_KEYS_DIR}/*.pem")

# Collect every .msg file found inside keys/key_verification_msgs/
file(GLOB MFG_MSG_FILES "${MFG_KEYS_DIR}/key_verification_msgs/*.msg")

# ---------------------------------------------------------------------------
# Run the Python conversion script at configure time to produce the header.
# Re-runs whenever a key or message file changes.
# ---------------------------------------------------------------------------
add_custom_command(
  OUTPUT  ${MFG_GEN_DIR}/provisioned_keys.h
  COMMAND ${PYTHON_EXECUTABLE}
          ${CMAKE_CURRENT_SOURCE_DIR}/cmake/pem_to_c.py
          --keys-dir   ${MFG_KEYS_DIR}
          --msgs-dir   ${MFG_KEYS_DIR}/key_verification_msgs
          --output     ${MFG_GEN_DIR}/provisioned_keys.h
  DEPENDS ${MFG_PEM_FILES} ${MFG_MSG_FILES}
          ${CMAKE_CURRENT_SOURCE_DIR}/cmake/pem_to_c.py
  COMMENT "Generating provisioned_keys.h from PEM files"
)

# ---------------------------------------------------------------------------
# Image digests: passed as CMake -D variables at build time, e.g.:
#   west build -- -DMFG_BL1_DIGEST=aabbcc...
# Defaults to all-zeros; a build with zeros will log a warning at runtime.
# ---------------------------------------------------------------------------
if(NOT DEFINED MFG_BL1_DIGEST)
  set(MFG_BL1_DIGEST "0000000000000000000000000000000000000000000000000000000000000000")
endif()
if(NOT DEFINED MFG_BL2A_DIGEST)
  set(MFG_BL2A_DIGEST "0000000000000000000000000000000000000000000000000000000000000000")
endif()
if(NOT DEFINED MFG_BL2B_DIGEST)
  set(MFG_BL2B_DIGEST "0000000000000000000000000000000000000000000000000000000000000000")
endif()
if(NOT DEFINED MFG_APP_CANDIDATE_DIGEST)
  set(MFG_APP_CANDIDATE_DIGEST "0000000000000000000000000000000000000000000000000000000000000000")
endif()

# Convert hex strings to C initializer lists (pairs of hex bytes)
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " BL1_BYTES   ${MFG_BL1_DIGEST})
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " BL2A_BYTES  ${MFG_BL2A_DIGEST})
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " BL2B_BYTES  ${MFG_BL2B_DIGEST})
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " APPC_BYTES  ${MFG_APP_CANDIDATE_DIGEST})

file(WRITE ${MFG_GEN_DIR}/image_digests.h
"/*
 * Auto-generated by cmake/keys.cmake — DO NOT EDIT.
 * Provide real digests via -DMFG_BL1_DIGEST=<hex64> etc. at build time.
 *
 * Copyright (c) 2025 Nordic Semiconductor ASA
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */
#ifndef IMAGE_DIGESTS_H_
#define IMAGE_DIGESTS_H_

#include <stdint.h>
#include <stdbool.h>

#define MFG_DIGEST_LEN 32U

static const uint8_t mfg_bl1_expected_digest[MFG_DIGEST_LEN]           = { ${BL1_BYTES} };
static const uint8_t mfg_bl2_slot_a_expected_digest[MFG_DIGEST_LEN]    = { ${BL2A_BYTES} };
static const uint8_t mfg_bl2_slot_b_expected_digest[MFG_DIGEST_LEN]    = { ${BL2B_BYTES} };
static const uint8_t mfg_app_candidate_expected_digest[MFG_DIGEST_LEN] = { ${APPC_BYTES} };

/* Returns true when a digest array consists entirely of zeros, which indicates
 * it was not provided at build time and validation should be skipped.
 */
static inline bool mfg_digest_is_zero(const uint8_t *digest)
{
	for (int i = 0; i < MFG_DIGEST_LEN; i++) {
		if (digest[i] != 0U) {
			return false;
		}
	}
	return true;
}

#endif /* IMAGE_DIGESTS_H_ */
"
)

add_custom_target(mfg_generate_keys DEPENDS ${MFG_GEN_DIR}/provisioned_keys.h)
add_dependencies(app mfg_generate_keys)
