#!/usr/bin/env python3
#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# pem_to_c.py
#
# Reads every *.pem file in --keys-dir and every *.msg file in --msgs-dir,
# then emits a C header file (--output) containing:
#
#   - A byte array for each public key (raw DER-decoded bytes).
#   - A byte array for each verification message / signature file.
#   - A table of mfg_key_info_t entries describing all keys.
#
# Usage:
#   python3 pem_to_c.py --keys-dir <dir> --msgs-dir <dir> --output <file.h>
#

import argparse
import base64
import os
import sys
import re

KNOWN_KEY_FINGERPRINTS = {
    # SHA-256 fingerprints of example/placeholder keys shipped with this sample.
    # Any key whose fingerprint appears here triggers a compile-time warning
    # reminding the developer to replace it with a production key.
    #
    # Add the fingerprint of each placeholder key from keys/*.pem here using:
    #   openssl pkey -in keys/urot_pubkey_gen0.pem -pubin -outform DER | sha256sum
}


def pem_to_der(pem_text):
    """Strip PEM armour and return raw DER bytes."""
    lines = pem_text.strip().splitlines()
    b64_lines = [l for l in lines if not l.startswith("-----")]
    return base64.b64decode("".join(b64_lines))


def bytes_to_c_array(name, data, comment=""):
    """Format a byte sequence as a C static const uint8_t array."""
    hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
    lines = []
    if comment:
        lines.append(f"/* {comment} */")
    lines.append(f"static const uint8_t {name}[] = {{")
    # Wrap at 12 bytes per line for readability
    chunk = 12
    raw = [f"0x{b:02x}" for b in data]
    for i in range(0, len(raw), chunk):
        lines.append("    " + ", ".join(raw[i:i + chunk]) + ",")
    lines.append("};")
    lines.append(f"static const size_t {name}_len = sizeof({name});")
    return "\n".join(lines)


def c_identifier(filename):
    """Convert a filename (without extension) to a valid C identifier."""
    base = os.path.splitext(os.path.basename(filename))[0]
    return re.sub(r"[^0-9a-zA-Z]", "_", base)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--keys-dir",  required=True)
    parser.add_argument("--msgs-dir",  required=True)
    parser.add_argument("--output",    required=True)
    args = parser.parse_args()

    pem_files = sorted(
        f for f in os.listdir(args.keys_dir) if f.endswith(".pem")
    )
    msg_files = []
    if os.path.isdir(args.msgs_dir):
        msg_files = sorted(
            f for f in os.listdir(args.msgs_dir) if f.endswith(".msg")
        )

    out = []
    out.append("/*")
    out.append(" * Auto-generated by cmake/pem_to_c.py — DO NOT EDIT.")
    out.append(" *")
    out.append(" * Copyright (c) 2025 Nordic Semiconductor ASA")
    out.append(" * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause")
    out.append(" */")
    out.append("#ifndef PROVISIONED_KEYS_H_")
    out.append("#define PROVISIONED_KEYS_H_")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include <stddef.h>")
    out.append("#include <stdbool.h>")
    out.append("")

    key_names = []

    for pem_file in pem_files:
        path = os.path.join(args.keys_dir, pem_file)
        with open(path, "r") as f:
            pem_text = f.read()

        # Detect placeholder / missing key
        is_placeholder = "REPLACE" in pem_text or "PLACEHOLDER" in pem_text

        if is_placeholder:
            name = c_identifier(pem_file)
            out.append(f"/* WARNING: {pem_file} is a placeholder key. */")
            out.append(f"/* Replace it with a real production key.    */")
            out.append(f"static const uint8_t {name}[] = {{0}};")
            out.append(f"static const size_t {name}_len = 0;")
            out.append(f"static const bool {name}_is_example = true;")
            out.append("")
            key_names.append((name, pem_file, True))
            continue

        try:
            der = pem_to_der(pem_text)
        except Exception as e:
            print(f"ERROR: Failed to decode {pem_file}: {e}", file=sys.stderr)
            sys.exit(1)

        name = c_identifier(pem_file)
        out.append(bytes_to_c_array(name, der, comment=f"Source: {pem_file}"))
        out.append(f"static const bool {name}_is_example = false;")
        out.append("")
        key_names.append((name, pem_file, False))

    # Verification messages
    out.append("/* Verification messages (pre-signed with the private key counterpart) */")
    for msg_file in msg_files:
        path = os.path.join(args.msgs_dir, msg_file)
        with open(path, "rb") as f:
            data = f.read()
        name = c_identifier(msg_file)
        out.append(bytes_to_c_array(name, data, comment=f"Source: {msg_file}"))
        out.append("")

    # Summary table
    out.append(f"#define MFG_NUM_UROT_KEYS {len(key_names)}U")
    out.append("")
    out.append("typedef struct {")
    out.append("    const char     *filename;")
    out.append("    const uint8_t  *data;")
    out.append("    size_t          len;")
    out.append("    bool            is_example;")
    out.append("} mfg_key_info_t;")
    out.append("")
    out.append("static const mfg_key_info_t mfg_urot_keys[] = {")
    for (name, fname, is_ex) in key_names:
        out.append(f'    {{ "{fname}", {name}, {name}_len, {str(is_ex).lower()} }},')
    out.append("};")
    out.append("")
    out.append("#endif /* PROVISIONED_KEYS_H_ */")

    with open(args.output, "w") as f:
        f.write("\n".join(out) + "\n")

    print(f"Generated: {args.output}  ({len(key_names)} keys, {len(msg_files)} messages)")


if __name__ == "__main__":
    main()
